//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace TestScriptLink2.ClientDemographicsWebSvc {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ClientDemographicsSoap", Namespace="http://tempuri.org")]
    public partial class ClientDemographics : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDictionaryItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateClientDemographicsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ClientDemographics() {
            this.Url = global::TestScriptLink2.Properties.Settings.Default.TestScriptLink2_ClientDemographics_ClientDemographics;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDictionaryItemsCompletedEventHandler GetDictionaryItemsCompleted;
        
        /// <remarks/>
        public event UpdateClientDemographicsCompletedEventHandler UpdateClientDemographicsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WEBSVC.ClientDemographics.GetDictionaryItems", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DictionaryItemObject[] GetDictionaryItems(string SystemCode, string UserName, string Password) {
            object[] results = this.Invoke("GetDictionaryItems", new object[] {
                        SystemCode,
                        UserName,
                        Password});
            return ((DictionaryItemObject[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDictionaryItemsAsync(string SystemCode, string UserName, string Password) {
            this.GetDictionaryItemsAsync(SystemCode, UserName, Password, null);
        }
        
        /// <remarks/>
        public void GetDictionaryItemsAsync(string SystemCode, string UserName, string Password, object userState) {
            if ((this.GetDictionaryItemsOperationCompleted == null)) {
                this.GetDictionaryItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDictionaryItemsOperationCompleted);
            }
            this.InvokeAsync("GetDictionaryItems", new object[] {
                        SystemCode,
                        UserName,
                        Password}, this.GetDictionaryItemsOperationCompleted, userState);
        }
        
        private void OnGetDictionaryItemsOperationCompleted(object arg) {
            if ((this.GetDictionaryItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDictionaryItemsCompleted(this, new GetDictionaryItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WEBSVC.ClientDemographics.UpdateClientDemographics", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebServiceResponse UpdateClientDemographics(string SystemCode, string UserName, string Password, ClientDemographicsObject ClientDemographicsInfo, string ClientID) {
            object[] results = this.Invoke("UpdateClientDemographics", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        ClientDemographicsInfo,
                        ClientID});
            return ((WebServiceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateClientDemographicsAsync(string SystemCode, string UserName, string Password, ClientDemographicsObject ClientDemographicsInfo, string ClientID) {
            this.UpdateClientDemographicsAsync(SystemCode, UserName, Password, ClientDemographicsInfo, ClientID, null);
        }
        
        /// <remarks/>
        public void UpdateClientDemographicsAsync(string SystemCode, string UserName, string Password, ClientDemographicsObject ClientDemographicsInfo, string ClientID, object userState) {
            if ((this.UpdateClientDemographicsOperationCompleted == null)) {
                this.UpdateClientDemographicsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateClientDemographicsOperationCompleted);
            }
            this.InvokeAsync("UpdateClientDemographics", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        ClientDemographicsInfo,
                        ClientID}, this.UpdateClientDemographicsOperationCompleted, userState);
        }
        
        private void OnUpdateClientDemographicsOperationCompleted(object arg) {
            if ((this.UpdateClientDemographicsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateClientDemographicsCompleted(this, new UpdateClientDemographicsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class DictionaryItemObject {
        
        private string dictionaryCodeField;
        
        private string dictionaryFieldDescriptionField;
        
        private string dictionaryUniqueIdField;
        
        private string dictionaryValueField;
        
        private string mesgField;
        
        private string statusField;
        
        /// <remarks/>
        public string DictionaryCode {
            get {
                return this.dictionaryCodeField;
            }
            set {
                this.dictionaryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DictionaryFieldDescription {
            get {
                return this.dictionaryFieldDescriptionField;
            }
            set {
                this.dictionaryFieldDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string DictionaryUniqueId {
            get {
                return this.dictionaryUniqueIdField;
            }
            set {
                this.dictionaryUniqueIdField = value;
            }
        }
        
        /// <remarks/>
        public string DictionaryValue {
            get {
                return this.dictionaryValueField;
            }
            set {
                this.dictionaryValueField = value;
            }
        }
        
        /// <remarks/>
        public string Mesg {
            get {
                return this.mesgField;
            }
            set {
                this.mesgField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class ResponseObject {
        
        private string confirmationField;
        
        private string messageField;
        
        private long statusField;
        
        private bool statusFieldSpecified;
        
        private string responseCodeField;
        
        private string uniqueIDField;
        
        /// <remarks/>
        public string Confirmation {
            get {
                return this.confirmationField;
            }
            set {
                this.confirmationField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public long Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UniqueID {
            get {
                return this.uniqueIDField;
            }
            set {
                this.uniqueIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class WebServiceResponse {
        
        private string confirmationField;
        
        private string messageField;
        
        private string responseCodeField;
        
        private ResponseObject[] responseObjectsField;
        
        private long statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        public string Confirmation {
            get {
                return this.confirmationField;
            }
            set {
                this.confirmationField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public ResponseObject[] ResponseObjects {
            get {
                return this.responseObjectsField;
            }
            set {
                this.responseObjectsField = value;
            }
        }
        
        /// <remarks/>
        public long Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class ClientDemographicsObject {
        
        private string englishProficiencyField;
        
        private string familySizeField;
        
        private string familyIncomeField;
        
        private string pregnancyStatusField;
        
        private string aliasField;
        
        private string alias10Field;
        
        private string alias2Field;
        
        private string alias3Field;
        
        private string alias4Field;
        
        private string alias5Field;
        
        private string alias6Field;
        
        private string alias7Field;
        
        private string alias8Field;
        
        private string alias9Field;
        
        private string citizenshipField;
        
        private string clientAddressCityField;
        
        private string clientAddressCountryField;
        
        private string clientAddressCountyField;
        
        private string clientAddressStateField;
        
        private string clientAddressStreetField;
        
        private string clientAddressStreet2Field;
        
        private string clientAddressZipcodeField;
        
        private string clientCellPhoneField;
        
        private string clientConfAddressCityField;
        
        private string clientConfAddressCountryField;
        
        private string clientConfAddressStateField;
        
        private string clientConfAddressStreetField;
        
        private string clientConfAddressStreet2Field;
        
        private string clientConfAddressZipcodeField;
        
        private string clientConfPhoneNumberField;
        
        private string clientEmailAddressField;
        
        private string clientFirstNameField;
        
        private string clientHomePhoneField;
        
        private string clientLastNameField;
        
        private string clientMailAddressCityField;
        
        private string clientMailAddressCountryField;
        
        private string clientMailAddressStateField;
        
        private string clientMailAddressStreetField;
        
        private string clientMailAddressStreet2Field;
        
        private string clientMailAddressZipcodeField;
        
        private string clientMiddleNameField;
        
        private string clientNameField;
        
        private string clientPrefixField;
        
        private string clientRaceField;
        
        private string clientSuffixField;
        
        private string clientWorkPhoneField;
        
        private string communicationPreferenceField;
        
        private string countryOfOriginField;
        
        private System.DateTime dateOfBirthField;
        
        private bool dateOfBirthFieldSpecified;
        
        private string educationField;
        
        private string employmentStatusField;
        
        private string ethnicOriginField;
        
        private string facilityChartNumberField;
        
        private string gUIDField;
        
        private string maidenNameField;
        
        private string maritalStatusField;
        
        private string occupationField;
        
        private string otherEthnicOriginsField;
        
        private string otherRacesField;
        
        private string clientDeclinedToProvideInfoField;
        
        private string placeOfBirthField;
        
        private string preferredProvidersEthnicOriginField;
        
        private string preferredProvidersSexField;
        
        private string primaryLanguageField;
        
        private string religionField;
        
        private string smokerField;
        
        private System.DateTime sSDemographicsDate1Field;
        
        private bool sSDemographicsDate1FieldSpecified;
        
        private System.DateTime sSDemographicsDate2Field;
        
        private bool sSDemographicsDate2FieldSpecified;
        
        private System.DateTime sSDemographicsDate3Field;
        
        private bool sSDemographicsDate3FieldSpecified;
        
        private System.DateTime sSDemographicsDate4Field;
        
        private bool sSDemographicsDate4FieldSpecified;
        
        private System.DateTime sSDemographicsDate5Field;
        
        private bool sSDemographicsDate5FieldSpecified;
        
        private string sSDemographicsDict1Field;
        
        private string sSDemographicsDict10Field;
        
        private string sSDemographicsDict2Field;
        
        private string sSDemographicsDict3Field;
        
        private string sSDemographicsDict4Field;
        
        private string sSDemographicsDict5Field;
        
        private string sSDemographicsDict6Field;
        
        private string sSDemographicsDict7Field;
        
        private string sSDemographicsDict8Field;
        
        private string sSDemographicsDict9Field;
        
        private string sSDemographicsFreeText201Field;
        
        private string sSDemographicsFreeText202Field;
        
        private string sSDemographicsFreeText203Field;
        
        private string sSDemographicsFreeText204Field;
        
        private string sSDemographicsFreeText205Field;
        
        private string sSDemographicsFreeText401Field;
        
        private string sSDemographicsFreeText402Field;
        
        private string sSDemographicsFreeText403Field;
        
        private string sSDemographicsFreeText404Field;
        
        private string sSDemographicsFreeText405Field;
        
        private string sSDemographicsMult1Field;
        
        private string sSDemographicsMult2Field;
        
        private string sSDemographicsMult3Field;
        
        private string sSDemographicsMult4Field;
        
        private string sSDemographicsMult5Field;
        
        private string sSDemographicsPhone1Field;
        
        private string sSDemographicsPhone2Field;
        
        private string sSDemographicsPhone3Field;
        
        private string sSDemographicsPhone4Field;
        
        private string sSDemographicsPhone5Field;
        
        private string sSDemographicsPractitioner1Field;
        
        private string sSDemographicsPractitioner2Field;
        
        private string sSDemographicsPractitioner3Field;
        
        private string sSDemographicsPractitioner4Field;
        
        private string sSDemographicsPractitioner5Field;
        
        private string sSDemographicsScrollFreeText1Field;
        
        private string sSDemographicsScrollFreeText2Field;
        
        private string sSDemographicsScrollFreeText3Field;
        
        private string sSDemographicsScrollFreeText4Field;
        
        private string sSDemographicsScrollFreeText5Field;
        
        private string sSDemographicsTime1Field;
        
        private string sSDemographicsTime2Field;
        
        private string sSDemographicsTime3Field;
        
        private string sSDemographicsTime4Field;
        
        private string sSDemographicsTime5Field;
        
        private string sexField;
        
        private string socialSecurityNumberField;
        
        private string socialSecurityNumber2Field;
        
        private string socialSecurityNumber3Field;
        
        private string socialSecurityNumber4Field;
        
        private string policyNumber1Field;
        
        private string guarantor1Field;
        
        private string policyNumber2Field;
        
        private string guarantor2Field;
        
        private string policyNumber3Field;
        
        private string guarantor3Field;
        
        private string policyNumber4Field;
        
        private string guarantor4Field;
        
        private string policyNumber5Field;
        
        private string guarantor5Field;
        
        private string policyNumber6Field;
        
        private string guarantor6Field;
        
        private string policyNumber7Field;
        
        private string guarantor7Field;
        
        private string policyNumber8Field;
        
        private string guarantor8Field;
        
        private string policyNumber9Field;
        
        private string guarantor9Field;
        
        private string policyNumber10Field;
        
        private string guarantor10Field;
        
        private System.DateTime uTCTimestampField;
        
        private bool uTCTimestampFieldSpecified;
        
        private System.DateTime expectedDueDateField;
        
        private bool expectedDueDateFieldSpecified;
        
        private string lactatingStatusField;
        
        /// <remarks/>
        public string EnglishProficiency {
            get {
                return this.englishProficiencyField;
            }
            set {
                this.englishProficiencyField = value;
            }
        }
        
        /// <remarks/>
        public string FamilySize {
            get {
                return this.familySizeField;
            }
            set {
                this.familySizeField = value;
            }
        }
        
        /// <remarks/>
        public string FamilyIncome {
            get {
                return this.familyIncomeField;
            }
            set {
                this.familyIncomeField = value;
            }
        }
        
        /// <remarks/>
        public string PregnancyStatus {
            get {
                return this.pregnancyStatusField;
            }
            set {
                this.pregnancyStatusField = value;
            }
        }
        
        /// <remarks/>
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        public string Alias10 {
            get {
                return this.alias10Field;
            }
            set {
                this.alias10Field = value;
            }
        }
        
        /// <remarks/>
        public string Alias2 {
            get {
                return this.alias2Field;
            }
            set {
                this.alias2Field = value;
            }
        }
        
        /// <remarks/>
        public string Alias3 {
            get {
                return this.alias3Field;
            }
            set {
                this.alias3Field = value;
            }
        }
        
        /// <remarks/>
        public string Alias4 {
            get {
                return this.alias4Field;
            }
            set {
                this.alias4Field = value;
            }
        }
        
        /// <remarks/>
        public string Alias5 {
            get {
                return this.alias5Field;
            }
            set {
                this.alias5Field = value;
            }
        }
        
        /// <remarks/>
        public string Alias6 {
            get {
                return this.alias6Field;
            }
            set {
                this.alias6Field = value;
            }
        }
        
        /// <remarks/>
        public string Alias7 {
            get {
                return this.alias7Field;
            }
            set {
                this.alias7Field = value;
            }
        }
        
        /// <remarks/>
        public string Alias8 {
            get {
                return this.alias8Field;
            }
            set {
                this.alias8Field = value;
            }
        }
        
        /// <remarks/>
        public string Alias9 {
            get {
                return this.alias9Field;
            }
            set {
                this.alias9Field = value;
            }
        }
        
        /// <remarks/>
        public string Citizenship {
            get {
                return this.citizenshipField;
            }
            set {
                this.citizenshipField = value;
            }
        }
        
        /// <remarks/>
        public string ClientAddressCity {
            get {
                return this.clientAddressCityField;
            }
            set {
                this.clientAddressCityField = value;
            }
        }
        
        /// <remarks/>
        public string ClientAddressCountry {
            get {
                return this.clientAddressCountryField;
            }
            set {
                this.clientAddressCountryField = value;
            }
        }
        
        /// <remarks/>
        public string ClientAddressCounty {
            get {
                return this.clientAddressCountyField;
            }
            set {
                this.clientAddressCountyField = value;
            }
        }
        
        /// <remarks/>
        public string ClientAddressState {
            get {
                return this.clientAddressStateField;
            }
            set {
                this.clientAddressStateField = value;
            }
        }
        
        /// <remarks/>
        public string ClientAddressStreet {
            get {
                return this.clientAddressStreetField;
            }
            set {
                this.clientAddressStreetField = value;
            }
        }
        
        /// <remarks/>
        public string ClientAddressStreet2 {
            get {
                return this.clientAddressStreet2Field;
            }
            set {
                this.clientAddressStreet2Field = value;
            }
        }
        
        /// <remarks/>
        public string ClientAddressZipcode {
            get {
                return this.clientAddressZipcodeField;
            }
            set {
                this.clientAddressZipcodeField = value;
            }
        }
        
        /// <remarks/>
        public string ClientCellPhone {
            get {
                return this.clientCellPhoneField;
            }
            set {
                this.clientCellPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string ClientConfAddressCity {
            get {
                return this.clientConfAddressCityField;
            }
            set {
                this.clientConfAddressCityField = value;
            }
        }
        
        /// <remarks/>
        public string ClientConfAddressCountry {
            get {
                return this.clientConfAddressCountryField;
            }
            set {
                this.clientConfAddressCountryField = value;
            }
        }
        
        /// <remarks/>
        public string ClientConfAddressState {
            get {
                return this.clientConfAddressStateField;
            }
            set {
                this.clientConfAddressStateField = value;
            }
        }
        
        /// <remarks/>
        public string ClientConfAddressStreet {
            get {
                return this.clientConfAddressStreetField;
            }
            set {
                this.clientConfAddressStreetField = value;
            }
        }
        
        /// <remarks/>
        public string ClientConfAddressStreet2 {
            get {
                return this.clientConfAddressStreet2Field;
            }
            set {
                this.clientConfAddressStreet2Field = value;
            }
        }
        
        /// <remarks/>
        public string ClientConfAddressZipcode {
            get {
                return this.clientConfAddressZipcodeField;
            }
            set {
                this.clientConfAddressZipcodeField = value;
            }
        }
        
        /// <remarks/>
        public string ClientConfPhoneNumber {
            get {
                return this.clientConfPhoneNumberField;
            }
            set {
                this.clientConfPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ClientEmailAddress {
            get {
                return this.clientEmailAddressField;
            }
            set {
                this.clientEmailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientFirstName {
            get {
                return this.clientFirstNameField;
            }
            set {
                this.clientFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string ClientHomePhone {
            get {
                return this.clientHomePhoneField;
            }
            set {
                this.clientHomePhoneField = value;
            }
        }
        
        /// <remarks/>
        public string ClientLastName {
            get {
                return this.clientLastNameField;
            }
            set {
                this.clientLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMailAddressCity {
            get {
                return this.clientMailAddressCityField;
            }
            set {
                this.clientMailAddressCityField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMailAddressCountry {
            get {
                return this.clientMailAddressCountryField;
            }
            set {
                this.clientMailAddressCountryField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMailAddressState {
            get {
                return this.clientMailAddressStateField;
            }
            set {
                this.clientMailAddressStateField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMailAddressStreet {
            get {
                return this.clientMailAddressStreetField;
            }
            set {
                this.clientMailAddressStreetField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMailAddressStreet2 {
            get {
                return this.clientMailAddressStreet2Field;
            }
            set {
                this.clientMailAddressStreet2Field = value;
            }
        }
        
        /// <remarks/>
        public string ClientMailAddressZipcode {
            get {
                return this.clientMailAddressZipcodeField;
            }
            set {
                this.clientMailAddressZipcodeField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMiddleName {
            get {
                return this.clientMiddleNameField;
            }
            set {
                this.clientMiddleNameField = value;
            }
        }
        
        /// <remarks/>
        public string ClientName {
            get {
                return this.clientNameField;
            }
            set {
                this.clientNameField = value;
            }
        }
        
        /// <remarks/>
        public string ClientPrefix {
            get {
                return this.clientPrefixField;
            }
            set {
                this.clientPrefixField = value;
            }
        }
        
        /// <remarks/>
        public string ClientRace {
            get {
                return this.clientRaceField;
            }
            set {
                this.clientRaceField = value;
            }
        }
        
        /// <remarks/>
        public string ClientSuffix {
            get {
                return this.clientSuffixField;
            }
            set {
                this.clientSuffixField = value;
            }
        }
        
        /// <remarks/>
        public string ClientWorkPhone {
            get {
                return this.clientWorkPhoneField;
            }
            set {
                this.clientWorkPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string CommunicationPreference {
            get {
                return this.communicationPreferenceField;
            }
            set {
                this.communicationPreferenceField = value;
            }
        }
        
        /// <remarks/>
        public string CountryOfOrigin {
            get {
                return this.countryOfOriginField;
            }
            set {
                this.countryOfOriginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateOfBirthSpecified {
            get {
                return this.dateOfBirthFieldSpecified;
            }
            set {
                this.dateOfBirthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Education {
            get {
                return this.educationField;
            }
            set {
                this.educationField = value;
            }
        }
        
        /// <remarks/>
        public string EmploymentStatus {
            get {
                return this.employmentStatusField;
            }
            set {
                this.employmentStatusField = value;
            }
        }
        
        /// <remarks/>
        public string EthnicOrigin {
            get {
                return this.ethnicOriginField;
            }
            set {
                this.ethnicOriginField = value;
            }
        }
        
        /// <remarks/>
        public string FacilityChartNumber {
            get {
                return this.facilityChartNumberField;
            }
            set {
                this.facilityChartNumberField = value;
            }
        }
        
        /// <remarks/>
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
            }
        }
        
        /// <remarks/>
        public string MaidenName {
            get {
                return this.maidenNameField;
            }
            set {
                this.maidenNameField = value;
            }
        }
        
        /// <remarks/>
        public string MaritalStatus {
            get {
                return this.maritalStatusField;
            }
            set {
                this.maritalStatusField = value;
            }
        }
        
        /// <remarks/>
        public string Occupation {
            get {
                return this.occupationField;
            }
            set {
                this.occupationField = value;
            }
        }
        
        /// <remarks/>
        public string OtherEthnicOrigins {
            get {
                return this.otherEthnicOriginsField;
            }
            set {
                this.otherEthnicOriginsField = value;
            }
        }
        
        /// <remarks/>
        public string OtherRaces {
            get {
                return this.otherRacesField;
            }
            set {
                this.otherRacesField = value;
            }
        }
        
        /// <remarks/>
        public string ClientDeclinedToProvideInfo {
            get {
                return this.clientDeclinedToProvideInfoField;
            }
            set {
                this.clientDeclinedToProvideInfoField = value;
            }
        }
        
        /// <remarks/>
        public string PlaceOfBirth {
            get {
                return this.placeOfBirthField;
            }
            set {
                this.placeOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string PreferredProvidersEthnicOrigin {
            get {
                return this.preferredProvidersEthnicOriginField;
            }
            set {
                this.preferredProvidersEthnicOriginField = value;
            }
        }
        
        /// <remarks/>
        public string PreferredProvidersSex {
            get {
                return this.preferredProvidersSexField;
            }
            set {
                this.preferredProvidersSexField = value;
            }
        }
        
        /// <remarks/>
        public string PrimaryLanguage {
            get {
                return this.primaryLanguageField;
            }
            set {
                this.primaryLanguageField = value;
            }
        }
        
        /// <remarks/>
        public string Religion {
            get {
                return this.religionField;
            }
            set {
                this.religionField = value;
            }
        }
        
        /// <remarks/>
        public string Smoker {
            get {
                return this.smokerField;
            }
            set {
                this.smokerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SSDemographicsDate1 {
            get {
                return this.sSDemographicsDate1Field;
            }
            set {
                this.sSDemographicsDate1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSDemographicsDate1Specified {
            get {
                return this.sSDemographicsDate1FieldSpecified;
            }
            set {
                this.sSDemographicsDate1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SSDemographicsDate2 {
            get {
                return this.sSDemographicsDate2Field;
            }
            set {
                this.sSDemographicsDate2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSDemographicsDate2Specified {
            get {
                return this.sSDemographicsDate2FieldSpecified;
            }
            set {
                this.sSDemographicsDate2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SSDemographicsDate3 {
            get {
                return this.sSDemographicsDate3Field;
            }
            set {
                this.sSDemographicsDate3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSDemographicsDate3Specified {
            get {
                return this.sSDemographicsDate3FieldSpecified;
            }
            set {
                this.sSDemographicsDate3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SSDemographicsDate4 {
            get {
                return this.sSDemographicsDate4Field;
            }
            set {
                this.sSDemographicsDate4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSDemographicsDate4Specified {
            get {
                return this.sSDemographicsDate4FieldSpecified;
            }
            set {
                this.sSDemographicsDate4FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SSDemographicsDate5 {
            get {
                return this.sSDemographicsDate5Field;
            }
            set {
                this.sSDemographicsDate5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSDemographicsDate5Specified {
            get {
                return this.sSDemographicsDate5FieldSpecified;
            }
            set {
                this.sSDemographicsDate5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsDict1 {
            get {
                return this.sSDemographicsDict1Field;
            }
            set {
                this.sSDemographicsDict1Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsDict10 {
            get {
                return this.sSDemographicsDict10Field;
            }
            set {
                this.sSDemographicsDict10Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsDict2 {
            get {
                return this.sSDemographicsDict2Field;
            }
            set {
                this.sSDemographicsDict2Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsDict3 {
            get {
                return this.sSDemographicsDict3Field;
            }
            set {
                this.sSDemographicsDict3Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsDict4 {
            get {
                return this.sSDemographicsDict4Field;
            }
            set {
                this.sSDemographicsDict4Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsDict5 {
            get {
                return this.sSDemographicsDict5Field;
            }
            set {
                this.sSDemographicsDict5Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsDict6 {
            get {
                return this.sSDemographicsDict6Field;
            }
            set {
                this.sSDemographicsDict6Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsDict7 {
            get {
                return this.sSDemographicsDict7Field;
            }
            set {
                this.sSDemographicsDict7Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsDict8 {
            get {
                return this.sSDemographicsDict8Field;
            }
            set {
                this.sSDemographicsDict8Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsDict9 {
            get {
                return this.sSDemographicsDict9Field;
            }
            set {
                this.sSDemographicsDict9Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsFreeText201 {
            get {
                return this.sSDemographicsFreeText201Field;
            }
            set {
                this.sSDemographicsFreeText201Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsFreeText202 {
            get {
                return this.sSDemographicsFreeText202Field;
            }
            set {
                this.sSDemographicsFreeText202Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsFreeText203 {
            get {
                return this.sSDemographicsFreeText203Field;
            }
            set {
                this.sSDemographicsFreeText203Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsFreeText204 {
            get {
                return this.sSDemographicsFreeText204Field;
            }
            set {
                this.sSDemographicsFreeText204Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsFreeText205 {
            get {
                return this.sSDemographicsFreeText205Field;
            }
            set {
                this.sSDemographicsFreeText205Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsFreeText401 {
            get {
                return this.sSDemographicsFreeText401Field;
            }
            set {
                this.sSDemographicsFreeText401Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsFreeText402 {
            get {
                return this.sSDemographicsFreeText402Field;
            }
            set {
                this.sSDemographicsFreeText402Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsFreeText403 {
            get {
                return this.sSDemographicsFreeText403Field;
            }
            set {
                this.sSDemographicsFreeText403Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsFreeText404 {
            get {
                return this.sSDemographicsFreeText404Field;
            }
            set {
                this.sSDemographicsFreeText404Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsFreeText405 {
            get {
                return this.sSDemographicsFreeText405Field;
            }
            set {
                this.sSDemographicsFreeText405Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsMult1 {
            get {
                return this.sSDemographicsMult1Field;
            }
            set {
                this.sSDemographicsMult1Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsMult2 {
            get {
                return this.sSDemographicsMult2Field;
            }
            set {
                this.sSDemographicsMult2Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsMult3 {
            get {
                return this.sSDemographicsMult3Field;
            }
            set {
                this.sSDemographicsMult3Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsMult4 {
            get {
                return this.sSDemographicsMult4Field;
            }
            set {
                this.sSDemographicsMult4Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsMult5 {
            get {
                return this.sSDemographicsMult5Field;
            }
            set {
                this.sSDemographicsMult5Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsPhone1 {
            get {
                return this.sSDemographicsPhone1Field;
            }
            set {
                this.sSDemographicsPhone1Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsPhone2 {
            get {
                return this.sSDemographicsPhone2Field;
            }
            set {
                this.sSDemographicsPhone2Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsPhone3 {
            get {
                return this.sSDemographicsPhone3Field;
            }
            set {
                this.sSDemographicsPhone3Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsPhone4 {
            get {
                return this.sSDemographicsPhone4Field;
            }
            set {
                this.sSDemographicsPhone4Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsPhone5 {
            get {
                return this.sSDemographicsPhone5Field;
            }
            set {
                this.sSDemographicsPhone5Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsPractitioner1 {
            get {
                return this.sSDemographicsPractitioner1Field;
            }
            set {
                this.sSDemographicsPractitioner1Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsPractitioner2 {
            get {
                return this.sSDemographicsPractitioner2Field;
            }
            set {
                this.sSDemographicsPractitioner2Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsPractitioner3 {
            get {
                return this.sSDemographicsPractitioner3Field;
            }
            set {
                this.sSDemographicsPractitioner3Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsPractitioner4 {
            get {
                return this.sSDemographicsPractitioner4Field;
            }
            set {
                this.sSDemographicsPractitioner4Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsPractitioner5 {
            get {
                return this.sSDemographicsPractitioner5Field;
            }
            set {
                this.sSDemographicsPractitioner5Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsScrollFreeText1 {
            get {
                return this.sSDemographicsScrollFreeText1Field;
            }
            set {
                this.sSDemographicsScrollFreeText1Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsScrollFreeText2 {
            get {
                return this.sSDemographicsScrollFreeText2Field;
            }
            set {
                this.sSDemographicsScrollFreeText2Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsScrollFreeText3 {
            get {
                return this.sSDemographicsScrollFreeText3Field;
            }
            set {
                this.sSDemographicsScrollFreeText3Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsScrollFreeText4 {
            get {
                return this.sSDemographicsScrollFreeText4Field;
            }
            set {
                this.sSDemographicsScrollFreeText4Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsScrollFreeText5 {
            get {
                return this.sSDemographicsScrollFreeText5Field;
            }
            set {
                this.sSDemographicsScrollFreeText5Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsTime1 {
            get {
                return this.sSDemographicsTime1Field;
            }
            set {
                this.sSDemographicsTime1Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsTime2 {
            get {
                return this.sSDemographicsTime2Field;
            }
            set {
                this.sSDemographicsTime2Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsTime3 {
            get {
                return this.sSDemographicsTime3Field;
            }
            set {
                this.sSDemographicsTime3Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsTime4 {
            get {
                return this.sSDemographicsTime4Field;
            }
            set {
                this.sSDemographicsTime4Field = value;
            }
        }
        
        /// <remarks/>
        public string SSDemographicsTime5 {
            get {
                return this.sSDemographicsTime5Field;
            }
            set {
                this.sSDemographicsTime5Field = value;
            }
        }
        
        /// <remarks/>
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        public string SocialSecurityNumber {
            get {
                return this.socialSecurityNumberField;
            }
            set {
                this.socialSecurityNumberField = value;
            }
        }
        
        /// <remarks/>
        public string SocialSecurityNumber2 {
            get {
                return this.socialSecurityNumber2Field;
            }
            set {
                this.socialSecurityNumber2Field = value;
            }
        }
        
        /// <remarks/>
        public string SocialSecurityNumber3 {
            get {
                return this.socialSecurityNumber3Field;
            }
            set {
                this.socialSecurityNumber3Field = value;
            }
        }
        
        /// <remarks/>
        public string SocialSecurityNumber4 {
            get {
                return this.socialSecurityNumber4Field;
            }
            set {
                this.socialSecurityNumber4Field = value;
            }
        }
        
        /// <remarks/>
        public string PolicyNumber1 {
            get {
                return this.policyNumber1Field;
            }
            set {
                this.policyNumber1Field = value;
            }
        }
        
        /// <remarks/>
        public string Guarantor1 {
            get {
                return this.guarantor1Field;
            }
            set {
                this.guarantor1Field = value;
            }
        }
        
        /// <remarks/>
        public string PolicyNumber2 {
            get {
                return this.policyNumber2Field;
            }
            set {
                this.policyNumber2Field = value;
            }
        }
        
        /// <remarks/>
        public string Guarantor2 {
            get {
                return this.guarantor2Field;
            }
            set {
                this.guarantor2Field = value;
            }
        }
        
        /// <remarks/>
        public string PolicyNumber3 {
            get {
                return this.policyNumber3Field;
            }
            set {
                this.policyNumber3Field = value;
            }
        }
        
        /// <remarks/>
        public string Guarantor3 {
            get {
                return this.guarantor3Field;
            }
            set {
                this.guarantor3Field = value;
            }
        }
        
        /// <remarks/>
        public string PolicyNumber4 {
            get {
                return this.policyNumber4Field;
            }
            set {
                this.policyNumber4Field = value;
            }
        }
        
        /// <remarks/>
        public string Guarantor4 {
            get {
                return this.guarantor4Field;
            }
            set {
                this.guarantor4Field = value;
            }
        }
        
        /// <remarks/>
        public string PolicyNumber5 {
            get {
                return this.policyNumber5Field;
            }
            set {
                this.policyNumber5Field = value;
            }
        }
        
        /// <remarks/>
        public string Guarantor5 {
            get {
                return this.guarantor5Field;
            }
            set {
                this.guarantor5Field = value;
            }
        }
        
        /// <remarks/>
        public string PolicyNumber6 {
            get {
                return this.policyNumber6Field;
            }
            set {
                this.policyNumber6Field = value;
            }
        }
        
        /// <remarks/>
        public string Guarantor6 {
            get {
                return this.guarantor6Field;
            }
            set {
                this.guarantor6Field = value;
            }
        }
        
        /// <remarks/>
        public string PolicyNumber7 {
            get {
                return this.policyNumber7Field;
            }
            set {
                this.policyNumber7Field = value;
            }
        }
        
        /// <remarks/>
        public string Guarantor7 {
            get {
                return this.guarantor7Field;
            }
            set {
                this.guarantor7Field = value;
            }
        }
        
        /// <remarks/>
        public string PolicyNumber8 {
            get {
                return this.policyNumber8Field;
            }
            set {
                this.policyNumber8Field = value;
            }
        }
        
        /// <remarks/>
        public string Guarantor8 {
            get {
                return this.guarantor8Field;
            }
            set {
                this.guarantor8Field = value;
            }
        }
        
        /// <remarks/>
        public string PolicyNumber9 {
            get {
                return this.policyNumber9Field;
            }
            set {
                this.policyNumber9Field = value;
            }
        }
        
        /// <remarks/>
        public string Guarantor9 {
            get {
                return this.guarantor9Field;
            }
            set {
                this.guarantor9Field = value;
            }
        }
        
        /// <remarks/>
        public string PolicyNumber10 {
            get {
                return this.policyNumber10Field;
            }
            set {
                this.policyNumber10Field = value;
            }
        }
        
        /// <remarks/>
        public string Guarantor10 {
            get {
                return this.guarantor10Field;
            }
            set {
                this.guarantor10Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UTCTimestamp {
            get {
                return this.uTCTimestampField;
            }
            set {
                this.uTCTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UTCTimestampSpecified {
            get {
                return this.uTCTimestampFieldSpecified;
            }
            set {
                this.uTCTimestampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ExpectedDueDate {
            get {
                return this.expectedDueDateField;
            }
            set {
                this.expectedDueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpectedDueDateSpecified {
            get {
                return this.expectedDueDateFieldSpecified;
            }
            set {
                this.expectedDueDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string LactatingStatus {
            get {
                return this.lactatingStatusField;
            }
            set {
                this.lactatingStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDictionaryItemsCompletedEventHandler(object sender, GetDictionaryItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDictionaryItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDictionaryItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DictionaryItemObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DictionaryItemObject[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateClientDemographicsCompletedEventHandler(object sender, UpdateClientDemographicsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateClientDemographicsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateClientDemographicsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebServiceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebServiceResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591