//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace TestScriptLink2.ClientChargeInput {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ClientChargeInputSoap", Namespace="http://tempuri.org")]
    public partial class ClientChargeInput : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FileClientChargeInputOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDictionaryItemsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ClientChargeInput() {
            this.Url = global::TestScriptLink2.Properties.Settings.Default.TestScriptLink2_ClientChargeInput_ClientChargeInput;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FileClientChargeInputCompletedEventHandler FileClientChargeInputCompleted;
        
        /// <remarks/>
        public event GetDictionaryItemsCompletedEventHandler GetDictionaryItemsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WEBSVC.ClientChargeInput.FileClientChargeInput", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebServiceResponse FileClientChargeInput(string SystemCode, string UserName, string Password, ClientChargeInputObject ClientChargeInputInfo) {
            object[] results = this.Invoke("FileClientChargeInput", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        ClientChargeInputInfo});
            return ((WebServiceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void FileClientChargeInputAsync(string SystemCode, string UserName, string Password, ClientChargeInputObject ClientChargeInputInfo) {
            this.FileClientChargeInputAsync(SystemCode, UserName, Password, ClientChargeInputInfo, null);
        }
        
        /// <remarks/>
        public void FileClientChargeInputAsync(string SystemCode, string UserName, string Password, ClientChargeInputObject ClientChargeInputInfo, object userState) {
            if ((this.FileClientChargeInputOperationCompleted == null)) {
                this.FileClientChargeInputOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFileClientChargeInputOperationCompleted);
            }
            this.InvokeAsync("FileClientChargeInput", new object[] {
                        SystemCode,
                        UserName,
                        Password,
                        ClientChargeInputInfo}, this.FileClientChargeInputOperationCompleted, userState);
        }
        
        private void OnFileClientChargeInputOperationCompleted(object arg) {
            if ((this.FileClientChargeInputCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FileClientChargeInputCompleted(this, new FileClientChargeInputCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WEBSVC.ClientChargeInput.GetDictionaryItems", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DictionaryItemObject[] GetDictionaryItems(string SystemCode, string UserName, string Password) {
            object[] results = this.Invoke("GetDictionaryItems", new object[] {
                        SystemCode,
                        UserName,
                        Password});
            return ((DictionaryItemObject[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDictionaryItemsAsync(string SystemCode, string UserName, string Password) {
            this.GetDictionaryItemsAsync(SystemCode, UserName, Password, null);
        }
        
        /// <remarks/>
        public void GetDictionaryItemsAsync(string SystemCode, string UserName, string Password, object userState) {
            if ((this.GetDictionaryItemsOperationCompleted == null)) {
                this.GetDictionaryItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDictionaryItemsOperationCompleted);
            }
            this.InvokeAsync("GetDictionaryItems", new object[] {
                        SystemCode,
                        UserName,
                        Password}, this.GetDictionaryItemsOperationCompleted, userState);
        }
        
        private void OnGetDictionaryItemsOperationCompleted(object arg) {
            if ((this.GetDictionaryItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDictionaryItemsCompleted(this, new GetDictionaryItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class ClientChargeInputObject {
        
        private string appointmentConfirmedField;
        
        private System.DateTime appointmentDateField;
        
        private bool appointmentDateFieldSpecified;
        
        private string appointmentEndTimeField;
        
        private string appointmentNotesField;
        
        private string appointmentSiteField;
        
        private string appointmentStartTimeField;
        
        private string appointmentStatusField;
        
        private string billableField;
        
        private string clientIDField;
        
        private string coPractitionerField;
        
        private string confirmationNotesField;
        
        private decimal costOfServiceField;
        
        private bool costOfServiceFieldSpecified;
        
        private System.DateTime dateOfServiceField;
        
        private bool dateOfServiceFieldSpecified;
        
        private long durationField;
        
        private bool durationFieldSpecified;
        
        private long episodeNumberField;
        
        private bool episodeNumberFieldSpecified;
        
        private long groupNumberField;
        
        private bool groupNumberFieldSpecified;
        
        private string locationField;
        
        private string medicalDiagnosis1Field;
        
        private string medicalDiagnosis2Field;
        
        private string missedVisitField;
        
        private string missedVisitNotesField;
        
        private string missedVisitServiceCodeField;
        
        private string modifiersField;
        
        private string noteReferenceCode837BillingField;
        
        private string noteReferenceText837BillingField;
        
        private long numberOfClientsField;
        
        private bool numberOfClientsFieldSpecified;
        
        private string oralCavityDesignationCodeField;
        
        private string practitionerField;
        
        private System.DateTime priorPlacementDateField;
        
        private bool priorPlacementDateFieldSpecified;
        
        private string programField;
        
        private string prosthesisCrownOrInlayCodeField;
        
        private string referringPractitionerField;
        
        private string referringProviderField;
        
        private string sSTxMultipleSelectDictionary1Field;
        
        private string sSTreatmentDSMCode1Field;
        
        private string sSTreatmentDSMCode2Field;
        
        private string sSTreatmentDSMCode3Field;
        
        private string sSTreatmentDSMCode4Field;
        
        private string sSTreatmentDSMCode5Field;
        
        private System.DateTime sSTreatmentDate1Field;
        
        private bool sSTreatmentDate1FieldSpecified;
        
        private System.DateTime sSTreatmentDate2Field;
        
        private bool sSTreatmentDate2FieldSpecified;
        
        private System.DateTime sSTreatmentDate3Field;
        
        private bool sSTreatmentDate3FieldSpecified;
        
        private System.DateTime sSTreatmentDate4Field;
        
        private bool sSTreatmentDate4FieldSpecified;
        
        private System.DateTime sSTreatmentDate5Field;
        
        private bool sSTreatmentDate5FieldSpecified;
        
        private string sSTreatmentDictionary1Field;
        
        private string sSTreatmentDictionary2Field;
        
        private string sSTreatmentDictionary3Field;
        
        private string sSTreatmentDictionary4Field;
        
        private string sSTreatmentDictionary5Field;
        
        private string sSTreatmentDictionary6Field;
        
        private string sSTreatmentDictionary7Field;
        
        private string sSTreatmentDictionary8Field;
        
        private string sSTreatmentDictionary9Field;
        
        private string sSTreatmentFreeText101Field;
        
        private string sSTreatmentFreeText102Field;
        
        private string sSTreatmentFreeText103Field;
        
        private string sSTreatmentFreeText104Field;
        
        private string sSTreatmentFreeText105Field;
        
        private string sSTreatmentFreeText401Field;
        
        private string sSTreatmentFreeText402Field;
        
        private string sSTreatmentFreeText403Field;
        
        private string sSTreatmentFreeText404Field;
        
        private string sSTreatmentFreeText405Field;
        
        private string sSTreatmentFreeText801Field;
        
        private string sSTreatmentFreeText802Field;
        
        private string sSTreatmentFreeText803Field;
        
        private string sSTreatmentFreeText804Field;
        
        private string sSTreatmentFreeText805Field;
        
        private string sSTreatmentGuarantor1Field;
        
        private string sSTreatmentGuarantor2Field;
        
        private string sSTreatmentGuarantor3Field;
        
        private string sSTreatmentGuarantor4Field;
        
        private string sSTreatmentGuarantor5Field;
        
        private string sSTreatmentICD9Code1Field;
        
        private string sSTreatmentICD9Code2Field;
        
        private string sSTreatmentICD9Code3Field;
        
        private string sSTreatmentICD9Code4Field;
        
        private string sSTreatmentICD9Code5Field;
        
        private string sSTreatmentPractitioner1Field;
        
        private string sSTreatmentPractitioner2Field;
        
        private string sSTreatmentPractitioner3Field;
        
        private string sSTreatmentPractitioner4Field;
        
        private string sSTreatmentPractitioner5Field;
        
        private string sSTreatmentScrollingFreeText1Field;
        
        private string sSTreatmentScrollingFreeText2Field;
        
        private string sSTreatmentScrollingFreeText3Field;
        
        private string sSTreatmentScrollingFreeText4Field;
        
        private string sSTreatmentScrollingFreeText5Field;
        
        private string sSTxMultipleSelectDictionary2Field;
        
        private string secondCoStaffMemberField;
        
        private string serviceCodeField;
        
        private string serviceEndTimeField;
        
        private string serviceStartTimeField;
        
        private string toothNumberField;
        
        private string toothStatusCodeField;
        
        private string toothSurfaceCodeField;
        
        private decimal unitsOfServiceField;
        
        private bool unitsOfServiceFieldSpecified;
        
        private string medicalDiagnosis3Field;
        
        private string medicalDiagnosis4Field;
        
        private string disciplineField;
        
        private string serviceStatusField;
        
        private System.DateTime initialTxDate2300DTP03Field;
        
        private bool initialTxDate2300DTP03FieldSpecified;
        
        private System.DateTime dateOfAccident2300DTP03Field;
        
        private bool dateOfAccident2300DTP03FieldSpecified;
        
        private string formLoc10AutoAccidentPlaceField;
        
        private string relatedCausesInfo2300CLM11Field;
        
        private System.DateTime firstBillingDateField;
        
        private bool firstBillingDateFieldSpecified;
        
        private long sSTreatmentInteger1Field;
        
        private bool sSTreatmentInteger1FieldSpecified;
        
        private long sSTreatmentInteger2Field;
        
        private bool sSTreatmentInteger2FieldSpecified;
        
        private long sSTreatmentInteger3Field;
        
        private bool sSTreatmentInteger3FieldSpecified;
        
        private long sSTreatmentInteger4Field;
        
        private bool sSTreatmentInteger4FieldSpecified;
        
        private long sSTreatmentInteger5Field;
        
        private bool sSTreatmentInteger5FieldSpecified;
        
        private long sSTreatmentInteger6Field;
        
        private bool sSTreatmentInteger6FieldSpecified;
        
        private string additionalServiceInformationField;
        
        private long psychotherapyAddOnDurationField;
        
        private bool psychotherapyAddOnDurationFieldSpecified;
        
        private string addOnNotesField;
        
        /// <remarks/>
        public string AppointmentConfirmed {
            get {
                return this.appointmentConfirmedField;
            }
            set {
                this.appointmentConfirmedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime AppointmentDate {
            get {
                return this.appointmentDateField;
            }
            set {
                this.appointmentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AppointmentDateSpecified {
            get {
                return this.appointmentDateFieldSpecified;
            }
            set {
                this.appointmentDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string AppointmentEndTime {
            get {
                return this.appointmentEndTimeField;
            }
            set {
                this.appointmentEndTimeField = value;
            }
        }
        
        /// <remarks/>
        public string AppointmentNotes {
            get {
                return this.appointmentNotesField;
            }
            set {
                this.appointmentNotesField = value;
            }
        }
        
        /// <remarks/>
        public string AppointmentSite {
            get {
                return this.appointmentSiteField;
            }
            set {
                this.appointmentSiteField = value;
            }
        }
        
        /// <remarks/>
        public string AppointmentStartTime {
            get {
                return this.appointmentStartTimeField;
            }
            set {
                this.appointmentStartTimeField = value;
            }
        }
        
        /// <remarks/>
        public string AppointmentStatus {
            get {
                return this.appointmentStatusField;
            }
            set {
                this.appointmentStatusField = value;
            }
        }
        
        /// <remarks/>
        public string Billable {
            get {
                return this.billableField;
            }
            set {
                this.billableField = value;
            }
        }
        
        /// <remarks/>
        public string ClientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        public string CoPractitioner {
            get {
                return this.coPractitionerField;
            }
            set {
                this.coPractitionerField = value;
            }
        }
        
        /// <remarks/>
        public string ConfirmationNotes {
            get {
                return this.confirmationNotesField;
            }
            set {
                this.confirmationNotesField = value;
            }
        }
        
        /// <remarks/>
        public decimal CostOfService {
            get {
                return this.costOfServiceField;
            }
            set {
                this.costOfServiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CostOfServiceSpecified {
            get {
                return this.costOfServiceFieldSpecified;
            }
            set {
                this.costOfServiceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DateOfService {
            get {
                return this.dateOfServiceField;
            }
            set {
                this.dateOfServiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateOfServiceSpecified {
            get {
                return this.dateOfServiceFieldSpecified;
            }
            set {
                this.dateOfServiceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DurationSpecified {
            get {
                return this.durationFieldSpecified;
            }
            set {
                this.durationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long EpisodeNumber {
            get {
                return this.episodeNumberField;
            }
            set {
                this.episodeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EpisodeNumberSpecified {
            get {
                return this.episodeNumberFieldSpecified;
            }
            set {
                this.episodeNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long GroupNumber {
            get {
                return this.groupNumberField;
            }
            set {
                this.groupNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GroupNumberSpecified {
            get {
                return this.groupNumberFieldSpecified;
            }
            set {
                this.groupNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string MedicalDiagnosis1 {
            get {
                return this.medicalDiagnosis1Field;
            }
            set {
                this.medicalDiagnosis1Field = value;
            }
        }
        
        /// <remarks/>
        public string MedicalDiagnosis2 {
            get {
                return this.medicalDiagnosis2Field;
            }
            set {
                this.medicalDiagnosis2Field = value;
            }
        }
        
        /// <remarks/>
        public string MissedVisit {
            get {
                return this.missedVisitField;
            }
            set {
                this.missedVisitField = value;
            }
        }
        
        /// <remarks/>
        public string MissedVisitNotes {
            get {
                return this.missedVisitNotesField;
            }
            set {
                this.missedVisitNotesField = value;
            }
        }
        
        /// <remarks/>
        public string MissedVisitServiceCode {
            get {
                return this.missedVisitServiceCodeField;
            }
            set {
                this.missedVisitServiceCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Modifiers {
            get {
                return this.modifiersField;
            }
            set {
                this.modifiersField = value;
            }
        }
        
        /// <remarks/>
        public string NoteReferenceCode837Billing {
            get {
                return this.noteReferenceCode837BillingField;
            }
            set {
                this.noteReferenceCode837BillingField = value;
            }
        }
        
        /// <remarks/>
        public string NoteReferenceText837Billing {
            get {
                return this.noteReferenceText837BillingField;
            }
            set {
                this.noteReferenceText837BillingField = value;
            }
        }
        
        /// <remarks/>
        public long NumberOfClients {
            get {
                return this.numberOfClientsField;
            }
            set {
                this.numberOfClientsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberOfClientsSpecified {
            get {
                return this.numberOfClientsFieldSpecified;
            }
            set {
                this.numberOfClientsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string OralCavityDesignationCode {
            get {
                return this.oralCavityDesignationCodeField;
            }
            set {
                this.oralCavityDesignationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Practitioner {
            get {
                return this.practitionerField;
            }
            set {
                this.practitionerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PriorPlacementDate {
            get {
                return this.priorPlacementDateField;
            }
            set {
                this.priorPlacementDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriorPlacementDateSpecified {
            get {
                return this.priorPlacementDateFieldSpecified;
            }
            set {
                this.priorPlacementDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Program {
            get {
                return this.programField;
            }
            set {
                this.programField = value;
            }
        }
        
        /// <remarks/>
        public string ProsthesisCrownOrInlayCode {
            get {
                return this.prosthesisCrownOrInlayCodeField;
            }
            set {
                this.prosthesisCrownOrInlayCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ReferringPractitioner {
            get {
                return this.referringPractitionerField;
            }
            set {
                this.referringPractitionerField = value;
            }
        }
        
        /// <remarks/>
        public string ReferringProvider {
            get {
                return this.referringProviderField;
            }
            set {
                this.referringProviderField = value;
            }
        }
        
        /// <remarks/>
        public string SSTxMultipleSelectDictionary1 {
            get {
                return this.sSTxMultipleSelectDictionary1Field;
            }
            set {
                this.sSTxMultipleSelectDictionary1Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentDSMCode1 {
            get {
                return this.sSTreatmentDSMCode1Field;
            }
            set {
                this.sSTreatmentDSMCode1Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentDSMCode2 {
            get {
                return this.sSTreatmentDSMCode2Field;
            }
            set {
                this.sSTreatmentDSMCode2Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentDSMCode3 {
            get {
                return this.sSTreatmentDSMCode3Field;
            }
            set {
                this.sSTreatmentDSMCode3Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentDSMCode4 {
            get {
                return this.sSTreatmentDSMCode4Field;
            }
            set {
                this.sSTreatmentDSMCode4Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentDSMCode5 {
            get {
                return this.sSTreatmentDSMCode5Field;
            }
            set {
                this.sSTreatmentDSMCode5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SSTreatmentDate1 {
            get {
                return this.sSTreatmentDate1Field;
            }
            set {
                this.sSTreatmentDate1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSTreatmentDate1Specified {
            get {
                return this.sSTreatmentDate1FieldSpecified;
            }
            set {
                this.sSTreatmentDate1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SSTreatmentDate2 {
            get {
                return this.sSTreatmentDate2Field;
            }
            set {
                this.sSTreatmentDate2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSTreatmentDate2Specified {
            get {
                return this.sSTreatmentDate2FieldSpecified;
            }
            set {
                this.sSTreatmentDate2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SSTreatmentDate3 {
            get {
                return this.sSTreatmentDate3Field;
            }
            set {
                this.sSTreatmentDate3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSTreatmentDate3Specified {
            get {
                return this.sSTreatmentDate3FieldSpecified;
            }
            set {
                this.sSTreatmentDate3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SSTreatmentDate4 {
            get {
                return this.sSTreatmentDate4Field;
            }
            set {
                this.sSTreatmentDate4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSTreatmentDate4Specified {
            get {
                return this.sSTreatmentDate4FieldSpecified;
            }
            set {
                this.sSTreatmentDate4FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SSTreatmentDate5 {
            get {
                return this.sSTreatmentDate5Field;
            }
            set {
                this.sSTreatmentDate5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSTreatmentDate5Specified {
            get {
                return this.sSTreatmentDate5FieldSpecified;
            }
            set {
                this.sSTreatmentDate5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentDictionary1 {
            get {
                return this.sSTreatmentDictionary1Field;
            }
            set {
                this.sSTreatmentDictionary1Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentDictionary2 {
            get {
                return this.sSTreatmentDictionary2Field;
            }
            set {
                this.sSTreatmentDictionary2Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentDictionary3 {
            get {
                return this.sSTreatmentDictionary3Field;
            }
            set {
                this.sSTreatmentDictionary3Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentDictionary4 {
            get {
                return this.sSTreatmentDictionary4Field;
            }
            set {
                this.sSTreatmentDictionary4Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentDictionary5 {
            get {
                return this.sSTreatmentDictionary5Field;
            }
            set {
                this.sSTreatmentDictionary5Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentDictionary6 {
            get {
                return this.sSTreatmentDictionary6Field;
            }
            set {
                this.sSTreatmentDictionary6Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentDictionary7 {
            get {
                return this.sSTreatmentDictionary7Field;
            }
            set {
                this.sSTreatmentDictionary7Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentDictionary8 {
            get {
                return this.sSTreatmentDictionary8Field;
            }
            set {
                this.sSTreatmentDictionary8Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentDictionary9 {
            get {
                return this.sSTreatmentDictionary9Field;
            }
            set {
                this.sSTreatmentDictionary9Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentFreeText101 {
            get {
                return this.sSTreatmentFreeText101Field;
            }
            set {
                this.sSTreatmentFreeText101Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentFreeText102 {
            get {
                return this.sSTreatmentFreeText102Field;
            }
            set {
                this.sSTreatmentFreeText102Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentFreeText103 {
            get {
                return this.sSTreatmentFreeText103Field;
            }
            set {
                this.sSTreatmentFreeText103Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentFreeText104 {
            get {
                return this.sSTreatmentFreeText104Field;
            }
            set {
                this.sSTreatmentFreeText104Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentFreeText105 {
            get {
                return this.sSTreatmentFreeText105Field;
            }
            set {
                this.sSTreatmentFreeText105Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentFreeText401 {
            get {
                return this.sSTreatmentFreeText401Field;
            }
            set {
                this.sSTreatmentFreeText401Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentFreeText402 {
            get {
                return this.sSTreatmentFreeText402Field;
            }
            set {
                this.sSTreatmentFreeText402Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentFreeText403 {
            get {
                return this.sSTreatmentFreeText403Field;
            }
            set {
                this.sSTreatmentFreeText403Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentFreeText404 {
            get {
                return this.sSTreatmentFreeText404Field;
            }
            set {
                this.sSTreatmentFreeText404Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentFreeText405 {
            get {
                return this.sSTreatmentFreeText405Field;
            }
            set {
                this.sSTreatmentFreeText405Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentFreeText801 {
            get {
                return this.sSTreatmentFreeText801Field;
            }
            set {
                this.sSTreatmentFreeText801Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentFreeText802 {
            get {
                return this.sSTreatmentFreeText802Field;
            }
            set {
                this.sSTreatmentFreeText802Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentFreeText803 {
            get {
                return this.sSTreatmentFreeText803Field;
            }
            set {
                this.sSTreatmentFreeText803Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentFreeText804 {
            get {
                return this.sSTreatmentFreeText804Field;
            }
            set {
                this.sSTreatmentFreeText804Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentFreeText805 {
            get {
                return this.sSTreatmentFreeText805Field;
            }
            set {
                this.sSTreatmentFreeText805Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentGuarantor1 {
            get {
                return this.sSTreatmentGuarantor1Field;
            }
            set {
                this.sSTreatmentGuarantor1Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentGuarantor2 {
            get {
                return this.sSTreatmentGuarantor2Field;
            }
            set {
                this.sSTreatmentGuarantor2Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentGuarantor3 {
            get {
                return this.sSTreatmentGuarantor3Field;
            }
            set {
                this.sSTreatmentGuarantor3Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentGuarantor4 {
            get {
                return this.sSTreatmentGuarantor4Field;
            }
            set {
                this.sSTreatmentGuarantor4Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentGuarantor5 {
            get {
                return this.sSTreatmentGuarantor5Field;
            }
            set {
                this.sSTreatmentGuarantor5Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentICD9Code1 {
            get {
                return this.sSTreatmentICD9Code1Field;
            }
            set {
                this.sSTreatmentICD9Code1Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentICD9Code2 {
            get {
                return this.sSTreatmentICD9Code2Field;
            }
            set {
                this.sSTreatmentICD9Code2Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentICD9Code3 {
            get {
                return this.sSTreatmentICD9Code3Field;
            }
            set {
                this.sSTreatmentICD9Code3Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentICD9Code4 {
            get {
                return this.sSTreatmentICD9Code4Field;
            }
            set {
                this.sSTreatmentICD9Code4Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentICD9Code5 {
            get {
                return this.sSTreatmentICD9Code5Field;
            }
            set {
                this.sSTreatmentICD9Code5Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentPractitioner1 {
            get {
                return this.sSTreatmentPractitioner1Field;
            }
            set {
                this.sSTreatmentPractitioner1Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentPractitioner2 {
            get {
                return this.sSTreatmentPractitioner2Field;
            }
            set {
                this.sSTreatmentPractitioner2Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentPractitioner3 {
            get {
                return this.sSTreatmentPractitioner3Field;
            }
            set {
                this.sSTreatmentPractitioner3Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentPractitioner4 {
            get {
                return this.sSTreatmentPractitioner4Field;
            }
            set {
                this.sSTreatmentPractitioner4Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentPractitioner5 {
            get {
                return this.sSTreatmentPractitioner5Field;
            }
            set {
                this.sSTreatmentPractitioner5Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentScrollingFreeText1 {
            get {
                return this.sSTreatmentScrollingFreeText1Field;
            }
            set {
                this.sSTreatmentScrollingFreeText1Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentScrollingFreeText2 {
            get {
                return this.sSTreatmentScrollingFreeText2Field;
            }
            set {
                this.sSTreatmentScrollingFreeText2Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentScrollingFreeText3 {
            get {
                return this.sSTreatmentScrollingFreeText3Field;
            }
            set {
                this.sSTreatmentScrollingFreeText3Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentScrollingFreeText4 {
            get {
                return this.sSTreatmentScrollingFreeText4Field;
            }
            set {
                this.sSTreatmentScrollingFreeText4Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTreatmentScrollingFreeText5 {
            get {
                return this.sSTreatmentScrollingFreeText5Field;
            }
            set {
                this.sSTreatmentScrollingFreeText5Field = value;
            }
        }
        
        /// <remarks/>
        public string SSTxMultipleSelectDictionary2 {
            get {
                return this.sSTxMultipleSelectDictionary2Field;
            }
            set {
                this.sSTxMultipleSelectDictionary2Field = value;
            }
        }
        
        /// <remarks/>
        public string SecondCoStaffMember {
            get {
                return this.secondCoStaffMemberField;
            }
            set {
                this.secondCoStaffMemberField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceCode {
            get {
                return this.serviceCodeField;
            }
            set {
                this.serviceCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceEndTime {
            get {
                return this.serviceEndTimeField;
            }
            set {
                this.serviceEndTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceStartTime {
            get {
                return this.serviceStartTimeField;
            }
            set {
                this.serviceStartTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ToothNumber {
            get {
                return this.toothNumberField;
            }
            set {
                this.toothNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ToothStatusCode {
            get {
                return this.toothStatusCodeField;
            }
            set {
                this.toothStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ToothSurfaceCode {
            get {
                return this.toothSurfaceCodeField;
            }
            set {
                this.toothSurfaceCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal UnitsOfService {
            get {
                return this.unitsOfServiceField;
            }
            set {
                this.unitsOfServiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnitsOfServiceSpecified {
            get {
                return this.unitsOfServiceFieldSpecified;
            }
            set {
                this.unitsOfServiceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string MedicalDiagnosis3 {
            get {
                return this.medicalDiagnosis3Field;
            }
            set {
                this.medicalDiagnosis3Field = value;
            }
        }
        
        /// <remarks/>
        public string MedicalDiagnosis4 {
            get {
                return this.medicalDiagnosis4Field;
            }
            set {
                this.medicalDiagnosis4Field = value;
            }
        }
        
        /// <remarks/>
        public string Discipline {
            get {
                return this.disciplineField;
            }
            set {
                this.disciplineField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceStatus {
            get {
                return this.serviceStatusField;
            }
            set {
                this.serviceStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime InitialTxDate2300DTP03 {
            get {
                return this.initialTxDate2300DTP03Field;
            }
            set {
                this.initialTxDate2300DTP03Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InitialTxDate2300DTP03Specified {
            get {
                return this.initialTxDate2300DTP03FieldSpecified;
            }
            set {
                this.initialTxDate2300DTP03FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DateOfAccident2300DTP03 {
            get {
                return this.dateOfAccident2300DTP03Field;
            }
            set {
                this.dateOfAccident2300DTP03Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateOfAccident2300DTP03Specified {
            get {
                return this.dateOfAccident2300DTP03FieldSpecified;
            }
            set {
                this.dateOfAccident2300DTP03FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string FormLoc10AutoAccidentPlace {
            get {
                return this.formLoc10AutoAccidentPlaceField;
            }
            set {
                this.formLoc10AutoAccidentPlaceField = value;
            }
        }
        
        /// <remarks/>
        public string RelatedCausesInfo2300CLM11 {
            get {
                return this.relatedCausesInfo2300CLM11Field;
            }
            set {
                this.relatedCausesInfo2300CLM11Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime FirstBillingDate {
            get {
                return this.firstBillingDateField;
            }
            set {
                this.firstBillingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FirstBillingDateSpecified {
            get {
                return this.firstBillingDateFieldSpecified;
            }
            set {
                this.firstBillingDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long SSTreatmentInteger1 {
            get {
                return this.sSTreatmentInteger1Field;
            }
            set {
                this.sSTreatmentInteger1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSTreatmentInteger1Specified {
            get {
                return this.sSTreatmentInteger1FieldSpecified;
            }
            set {
                this.sSTreatmentInteger1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long SSTreatmentInteger2 {
            get {
                return this.sSTreatmentInteger2Field;
            }
            set {
                this.sSTreatmentInteger2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSTreatmentInteger2Specified {
            get {
                return this.sSTreatmentInteger2FieldSpecified;
            }
            set {
                this.sSTreatmentInteger2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long SSTreatmentInteger3 {
            get {
                return this.sSTreatmentInteger3Field;
            }
            set {
                this.sSTreatmentInteger3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSTreatmentInteger3Specified {
            get {
                return this.sSTreatmentInteger3FieldSpecified;
            }
            set {
                this.sSTreatmentInteger3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long SSTreatmentInteger4 {
            get {
                return this.sSTreatmentInteger4Field;
            }
            set {
                this.sSTreatmentInteger4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSTreatmentInteger4Specified {
            get {
                return this.sSTreatmentInteger4FieldSpecified;
            }
            set {
                this.sSTreatmentInteger4FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long SSTreatmentInteger5 {
            get {
                return this.sSTreatmentInteger5Field;
            }
            set {
                this.sSTreatmentInteger5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSTreatmentInteger5Specified {
            get {
                return this.sSTreatmentInteger5FieldSpecified;
            }
            set {
                this.sSTreatmentInteger5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long SSTreatmentInteger6 {
            get {
                return this.sSTreatmentInteger6Field;
            }
            set {
                this.sSTreatmentInteger6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSTreatmentInteger6Specified {
            get {
                return this.sSTreatmentInteger6FieldSpecified;
            }
            set {
                this.sSTreatmentInteger6FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string AdditionalServiceInformation {
            get {
                return this.additionalServiceInformationField;
            }
            set {
                this.additionalServiceInformationField = value;
            }
        }
        
        /// <remarks/>
        public long PsychotherapyAddOnDuration {
            get {
                return this.psychotherapyAddOnDurationField;
            }
            set {
                this.psychotherapyAddOnDurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PsychotherapyAddOnDurationSpecified {
            get {
                return this.psychotherapyAddOnDurationFieldSpecified;
            }
            set {
                this.psychotherapyAddOnDurationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string AddOnNotes {
            get {
                return this.addOnNotesField;
            }
            set {
                this.addOnNotesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class DictionaryItemObject {
        
        private string dictionaryCodeField;
        
        private string dictionaryFieldDescriptionField;
        
        private string dictionaryUniqueIdField;
        
        private string dictionaryValueField;
        
        private string mesgField;
        
        private string statusField;
        
        /// <remarks/>
        public string DictionaryCode {
            get {
                return this.dictionaryCodeField;
            }
            set {
                this.dictionaryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DictionaryFieldDescription {
            get {
                return this.dictionaryFieldDescriptionField;
            }
            set {
                this.dictionaryFieldDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string DictionaryUniqueId {
            get {
                return this.dictionaryUniqueIdField;
            }
            set {
                this.dictionaryUniqueIdField = value;
            }
        }
        
        /// <remarks/>
        public string DictionaryValue {
            get {
                return this.dictionaryValueField;
            }
            set {
                this.dictionaryValueField = value;
            }
        }
        
        /// <remarks/>
        public string Mesg {
            get {
                return this.mesgField;
            }
            set {
                this.mesgField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class ResponseObject {
        
        private string confirmationField;
        
        private string messageField;
        
        private long statusField;
        
        private bool statusFieldSpecified;
        
        private string responseCodeField;
        
        private string uniqueIDField;
        
        /// <remarks/>
        public string Confirmation {
            get {
                return this.confirmationField;
            }
            set {
                this.confirmationField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public long Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UniqueID {
            get {
                return this.uniqueIDField;
            }
            set {
                this.uniqueIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class WebServiceResponse {
        
        private string confirmationField;
        
        private string messageField;
        
        private string responseCodeField;
        
        private ResponseObject[] responseObjectsField;
        
        private long statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        public string Confirmation {
            get {
                return this.confirmationField;
            }
            set {
                this.confirmationField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public ResponseObject[] ResponseObjects {
            get {
                return this.responseObjectsField;
            }
            set {
                this.responseObjectsField = value;
            }
        }
        
        /// <remarks/>
        public long Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FileClientChargeInputCompletedEventHandler(object sender, FileClientChargeInputCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FileClientChargeInputCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FileClientChargeInputCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebServiceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebServiceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDictionaryItemsCompletedEventHandler(object sender, GetDictionaryItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDictionaryItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDictionaryItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DictionaryItemObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DictionaryItemObject[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591